config/routes.rb
WazaTask::Application.routes.draw do
  root "welcome#index"

  get "welcome/spike"
  
  get "tasks/index"
  get "tasks/baus"
  get "tasks/projects"
  get "tasks/huddle"
  get "tasks/dashboard"
  get "tasks/issues"
  get "tasks/calendar"
  get "accountsfile/index"
  get "tasks/profile"

  resources :tasks

  devise_for :users

end

app/models/bau.rb
class Bau < Task

#to extract as now in Task

	scope :current_month, -> {
		where(due_date: (Time.now.beginning_of_month..Time.now.end_of_month))
	}

	scope :previous_month, -> {
		where(due_date: (1.month.ago.beginning_of_month..1.month.ago.end_of_month))
	}

	scope :status_to_do, -> {
		where(status: 'To Do')
	}

	scope :status_in_progress, -> {
		where(status: 'In-Progress')
	}

	scope :status_complete, -> {
		where(status: 'Complete')
	}

	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/project.rb
class Project < Task

	scope :current_month, -> {
		where(due_date: (Time.now.beginning_of_month..Time.now.end_of_month))
	}

	scope :previous_month, -> {
		where(due_date: (1.month.ago.beginning_of_month..1.month.ago.end_of_month))
	}

	scope :status_to_do, -> {
		where(status: 'To Do')
	}

	scope :status_in_progress, -> {
		where(status: 'In-Progress')
	}

	scope :status_complete, -> {
		where(status: 'Complete')
	}

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :team
  has_many :comments

  def self.select_options(child)
    [["Bau","Bau"],["Project","Project"]]
  end

    scope :current_month, -> {
		where(due_date: (Time.now.beginning_of_month..Time.now.end_of_month))
	}

	scope :previous_month, -> {
		where(due_date: (1.month.ago.beginning_of_month..1.month.ago.end_of_month))
	}

	scope :status_to_do, -> {
		where(status: 'To Do')
	}

	scope :status_in_progress, -> {
		where(status: 'In-Progress')
	}

	scope :status_complete, -> {
		where(status: 'Complete')
	}


 #  @child_classes = []

	# def self.inherited(child)
	#   @child_classes << child
	#   super # important!
	# end

	# def self.child_classes
	#   @child_classes
	# end

end

app/models/team.rb
class Team < ActiveRecord::Base

  has_many :users
  has_many :tasks
  has_many :projects
  has_many :baus
  # after_create :add_task


  def tasks_by_type_and_month
    {:baus_this_month => baus.current_month, 
     :projects_this_month => projects.current_month,
       :baus_previous_month => projects.previous_month,
       :projects_previous_month => projects.previous_month,
         :tasks_this_month => tasks.current_month,
         :tasks_previous_month => tasks.previous_month
    }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :team
  has_many :comments

end

app/controllers/accountsfile_controller.rb
class AccountsfileController < ApplicationController
  def index

    
  end

 
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :json
  
  def index
    # raise current_user.team_id.inspect
    # @tasks = Task.all.where("team_id = ?", current_user.team_id)
    @tasks = current_user.team.tasks
    # @team = Team.find(current_user.team_id)
  end

  def new
    @team = current_user.team
    @task = @team.tasks.new
  end

  def create
    @team = current_user.team
    @task = @team.tasks.create(params[:task].permit(:description, :owner, :due_date, :actual_hrs, :status, :user_id, :type, :report_tag, :expected_hrs, :requested_by, :time))
    redirect_to tasks_calendar_path
  end

  def baus
    @tasks = Bau.all
  end

  def projects
    @task = Project.all.last
  end

  def huddle
  end

  def dashboard
  end

  def issues
    @tasks = Task.current_month
    @date = Date.today
  end

  def calendar
    @date = Date.today
    @calendar_views = [Task.current_month, Task.previous_month, Task.current_month, Task.previous_month]
  end

  def show
    @task = Task.find(params[:id])
  end

  def profile
    render json: current_user.team.tasks.last(5) 
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	if user_signed_in?
  	else
  		redirect_to new_user_session_path
  	end
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/task/calendar.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'calendar_better.jpg'%>" />
	   <img src="<%= asset_path 'calendar_better.jpg'%>" />
	  <img src="<%= asset_path 'calendar_better.jpg'%>" />
	   <img src="<%= asset_path 'calendar_better.jpg'%>" />
	 <img src="<%= asset_path 'calendar_better.jpg'%>" />
	</div>
<!-- </div> -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript" src="<%= asset_path 'jquery.waterwheelCarousel.js'%>"></script>

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/task/dashboard.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>s

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	</div>
<!-- </div> -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript" src="<%= asset_path 'jquery.waterwheelCarousel.js'%>"></script>

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/task/huddle.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'huddleboard.jpeg'%>" />
	  <img src="<%= asset_path 'huddleboard.jpeg'%>" />
	  <img src="<%= asset_path 'huddleboard.jpeg'%>" />
	  <img src="<%= asset_path 'huddleboard.jpeg'%>" />
	  <img src="<%= asset_path 'huddleboard.jpeg'%>" />
	</div>
<!-- </div> -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript" src="<%= asset_path 'jquery.waterwheelCarousel.js'%>"></script>

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/task/index.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>s

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'Calendar.jpg'%>" />
	  <img src="<%= asset_path 'Calendar.jpg'%>" />
	  <img src="<%= asset_path 'Calendar.jpg'%>" />
	  <img src="<%= asset_path 'Calendar.jpg'%>" />
	  <img src="<%= asset_path 'Calendar.jpg'%>" />
	</div>
<!-- </div> -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript" src="<%= asset_path 'jquery.waterwheelCarousel.js'%>"></script>

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/task/issues.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'issues_card.jpg'%>" />
	  <img src="<%= asset_path 'issues_card.jpg'%>" />
	  <img src="<%= asset_path 'issues_card.jpg'%>" />
    <img src="<%= asset_path 'issues_card.jpg'%>" />
	  <img src="<%= asset_path 'issues_card.jpg'%>" />
    <img src="<%= asset_path 'issues_card.jpg'%>" />
    <img src="<%= asset_path 'issues_card.jpg'%>" />
	</div>
<!-- </div> -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript" src="<%= asset_path 'jquery.waterwheelCarousel.js'%>"></script>

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/task/projects.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>

<!-- <div class="view_container"> -->
  <div id="view_carousel">
    <img src="<%= asset_path 'projects.png'%>" />
    <img src="<%= asset_path 'projects.png'%>" />
    <img src="<%= asset_path 'projects.png'%>" />
    <img src="<%= asset_path 'projects.png'%>" />
    <img src="<%= asset_path 'projects.png'%>" />
  </div>
<!-- </div> -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript" src="<%= asset_path 'jquery.waterwheelCarousel.js'%>"></script>

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>
</script>

app/views/task/show.html.erb
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', task_calendar_path %></li>
    <li><%= link_to 'Huddle', task_huddle_path %></li>
    <li><%= link_to 'Dashboard', task_dashboard_path %></li>
    <li><%= link_to 'BAU', task_baus_path %></li>
    <li><%= link_to 'Projects', task_projects_path %></li>
    <li><%= link_to 'Issues', task_issues_path %></li>
  </ul>
</div>

<div class="card_show_container">

<div class="left_block">
 	  <p>Task Description</p>
 	  <p>This is the description the task</p>

 	  <p>Task Due Date</p>
 	  <p>11th January 2014</p>
 
 	  <p>Customer</p>
 	  <p>Internal management</p>
</div>

  <div class="comment_list_container">
      <p>Comments:</p>
    <div class="comment_container">
      <p>This is a comment for the task</p>
      <span> Commented by: Simon </span>
    </div>
    <div class="comment_container">
      <p>This is a comment for the task</p>
      <span> Commented by: Simon </span>
    </div>
    <div class="comment_container">
      <p>This is a comment for the task</p>
      <span> Commented by: Simon </span>
    </div>
  </div>

  <div class="status_position">
     <p>Task Status</p>
     <p>In-progress</p>
   </div>
  

</div>

app/views/tasks/baus.html.erb
<div class="dotted_backgroud">
  <div class="task_management">
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', tasks_calendar_path %></li>
    <li><%= link_to 'Huddle', tasks_huddle_path %></li>
    <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
    <li><%= link_to 'BAU', tasks_baus_path %></li>
    <li><%= link_to 'Projects', tasks_projects_path %></li>
    <li><%= link_to 'Issues', tasks_issues_path %></li>
  </ul>
</div>
</div>

<!-- <div class="view_container"> -->
  <div id="view_carousel">
    <% if @tasks.empty? %>
      No tasks yet.
    <% end %>
    <% @tasks.each do |task| %>
     <li>
      <%= link_to task_path task do%>
      <%# render 'tasks_card', task: task %>
      <div id="task_text">
        <%= task.description %><br>
      </div>
      <div id="owner">
        <%= task.owner %><br>
      </div>
        <div id="tags">
        <%= task.report_tag %>
      </div>
      <%= task.due_date %><br>
      <%= task.status %><br>
      <%= task.type %><br>
      <%= task.expected_hrs %><br>
      <%= task.requested_by %><br>
      <%= task.time %><br>

      <% end %>
    </li>
    <% end %>
  </div>
</div>
<!-- </div> -->


<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true,
    selector: 'li',
    preloadImages: false,
    clickedCenter: function(element) {
      window.location.href=element.children('a').attr('href');
    }
  });
});

</script>

app/views/tasks/calendar.html.erb
<div class="dotted_backgroud">
  <div class="task_management">
  

  <div class="nav_container">
    <ul>
      <li><%= link_to 'Calendar', tasks_calendar_path %></li>
      <li><%= link_to 'Huddle', tasks_huddle_path %></li>
      <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
      <li><%= link_to 'BAU', tasks_baus_path %></li>
      <li><%= link_to 'Projects', tasks_projects_path %></li>
      <li><%= link_to 'Issues', tasks_issues_path %></li>
    </ul>
  </div>
  </div>

  <!-- <div class="view_container"> -->
  <div id="view_carousel">
    <% @calendar_views.each do |calendar| %> 
    <%= calendar_for(calendar, :year => @date.year, :month => @date.month) do |calendar| %>
  <%= calendar.head('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun') %>
  <%= calendar.day(:day_method => :due_date) do |date, tasks| %>
  <div class="day_block">
  <%= date.day %>
  <% tasks.each do |task| %>
  <div class="task_card">
  <%= link_to task.type, task_path(task) %>
  </div>
  <% end %>
  </div>
  <% end %>
  <% end %>
  <% end %>
  </div>
  </div>


  <!-- </div> -->



<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true,
    selector: 'table',
    preloadImages: false,
    clickedCenter: function(element) {
      // window.location.href=element.children('a').attr('href');
    }
  });
});

$(".task_card a").click(function() {
  window.location = $(this).attr('href');
});



</script>

app/views/tasks/dashboard.html.erb
<div class="dotted_backgroud">
  <div class="task_management">
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', tasks_calendar_path %></li>
    <li><%= link_to 'Huddle', tasks_huddle_path %></li>
    <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
    <li><%= link_to 'BAU', tasks_baus_path %></li>
    <li><%= link_to 'Projects', tasks_projects_path %></li>
    <li><%= link_to 'Issues', tasks_issues_path %></li>
  </ul>
</div>
</div>

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	  <img src="<%= asset_path 'OnTimeDashboard1.png'%>" />
	</div>

</div>
<!-- </div> -->


<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/tasks/huddle.html.erb
<div class="dotted_backgroud">
  <div class="task_management">
<div class="nav_container">

  <ul>
    <li><%= link_to 'Calendar', tasks_calendar_path %></li>
    <li><%= link_to 'Huddle', tasks_huddle_path %></li>
    <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
    <li><%= link_to 'BAU', tasks_baus_path %></li>
    <li><%= link_to 'Projects', tasks_projects_path %></li>
    <li><%= link_to 'Issues', tasks_issues_path %></li>
  </ul>
</div>
</div>

<!-- <div class="view_container"> -->
	<div id="view_carousel">
	  <img src="<%= asset_path 'calendar_place_holder.png'%>" />
       <img src="<%= asset_path 'calendar_place_holder.png'%>" />
      <img src="<%= asset_path 'calendar_place_holder.png'%>" />
       <img src="<%= asset_path 'calendar_place_holder.png'%>" />
     <img src="<%= asset_path 'calendar_place_holder.png'%>" />
	</div>
</div>
<!-- </div> -->

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true
  });
});

</script>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
<p><%= task.description %></p>
<p><%= task.type %></p>
<p><%= task.team_id %></p>
<% end %>

<h1><%= current_user.team_id %></h1>





 

app/views/tasks/issues.html.erb
<div class="dotted_backgroud">
  <div class="task_management">
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', tasks_calendar_path %></li>
    <li><%= link_to 'Huddle', tasks_huddle_path %></li>
    <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
    <li><%= link_to 'BAU', tasks_baus_path %></li>
    <li><%= link_to 'Projects', tasks_projects_path %></li>
    <li><%= link_to 'Issues', tasks_issues_path %></li>
  </ul>
</div>
</div>

<!-- <div class="view_container"> -->
  <div id="view_carousel">
<%= calendar_for(@tasks, :year => @date.year, :month => @date.month) do |calendar| %>
  <%= calendar.head('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun') %>
  <%= calendar.day(:day_method => :due_date) do |date, tasks| %>
  <div class="day_block">
    <%= date.day %>
  <% tasks.each do |task| %>
  <div class="task_card">
  <%= link_to task.type, task_path(task) %>
  </div>
  <% end %>
</div>
  <% end %>
<% end %>
<%= calendar_for(@tasks, :year => @date.year, :month => @date.month) do |calendar| %>
  <%= calendar.head('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun') %>
  <%= calendar.day(:day_method => :due_date) do |date, tasks| %>
  <div class="day_block">
    <%= date.day %>
  <% tasks.each do |task| %>
  <div class="task_card">
  <%= link_to task.type, task_path(task) %>
  </div>
  <% end %>
</div>
  <% end %>
<% end %>
<%= calendar_for(@tasks, :year => @date.year, :month => @date.month) do |calendar| %>
  <%= calendar.head('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun') %>
  <%= calendar.day(:day_method => :due_date) do |date, tasks| %>
  <div class="day_block">
    <%= date.day %>
  <% tasks.each do |task| %>
  <div class="task_card">
  <%= link_to task.type, task_path(task) %>
  </div>
  <% end %>
</div>
  <% end %>
<% end %>
</div>

<!-- </div> -->

<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true,
    selector: 'table',
    preloadImages: false,
    clickedCenter: function(element) {
      window.location.href=element.children('a').attr('href');
    }
  });
});

</script>

app/views/tasks/projects.html.erb
<div class="dotted_backgroud">
  <div class="task_management">
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', tasks_calendar_path %></li>
    <li><%= link_to 'Huddle', tasks_huddle_path %></li>
    <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
    <li><%= link_to 'BAU', tasks_baus_path %></li>
    <li><%= link_to 'Projects', tasks_projects_path %></li>
    <li><%= link_to 'Issues', tasks_issues_path %></li>
  </ul>
</div>
</div>

<!-- <div class="view_container"> -->
  <div id="view_carousel">
  <li>
      <div class="card_show_container">

  <div class="comment_list_container">
      <span>Comments:</span>
  <%#@task.comments.each do |comment| %>
    <div class="comment_container">
      <p><%#= comment.description %></p>
      <span> Commented by: comment.user_id.email </span>
    </div>
  <%# end %>
  </div>

  <div class="bottom_left">
    asdasdasdasdasd
  </div>

  <div class="right_block2">
    <div class="description">
      <span>Task Description</span>
      <p><%= @task.description%></p>
    </div>  
    <div class="description">
      <span>Date due</span>
      <p><%=@task.due_date%></p>
    </div>
    <div class="description">
      <span>Time due</span>
      <p><%=@task.time%></p>
    </div>
    <div class="description">
      <span>Task Owner</span>
      <p><%=@task.owner%></p>
    </div>
    <div class="description">
      <span>Expected Hours</span>
      <p><%=@task.expected_hrs%></p>
    </div>
    <div class="description">
      <span>Task Status</span>
      <p><%= @task.status%></p>
    </div>
    <div class="description">
      <span>Requested by</span>
      <p><%= @task.requested_by%></p>
    </div>
    <div class="description">
      <span>Report Tag</span>
      <p><%= @task.report_tag%></p>
    </div>
  </div>
</li>

</div>
  </div>
</div>
<!-- </div> -->





<script>

$(document).ready(function () {
  $("#view_carousel").waterwheelCarousel({
    horizon: 110,
    horizonOffset: -50,
    horizonOffsetMultiplier: .7,
    separation: 250,
    edgeFadeEnabled: true,
    selector: 'li',
    preloadImages: false,
    clickedCenter: function(element) {
      window.location.href=element.children('a').attr('href');
    }
  });
});

</script>

app/views/tasks/show.html.erb
<div class="dotted_backgroud">

<div class="task_management">
<div class="nav_container">
  <ul>
    <li><%= link_to 'Calendar', tasks_calendar_path %></li>
    <li><%= link_to 'Huddle', tasks_huddle_path %></li>
    <li><%= link_to 'Dashboard', tasks_dashboard_path %></li>
    <li><%= link_to 'BAU', tasks_baus_path %></li>
    <li><%= link_to 'Projects', tasks_projects_path %></li>
    <li><%= link_to 'Issues', tasks_issues_path %></li>
  </ul>
</div>
</div>

<%= stylesheet_link_tag "card_show" %>
<%#= @task.inspect %>
<%#= render 'tasks_card', task: @task %>
  <div class="card_show_container">

  <div class="comment_list_container">
   	  <span>Comments:</span>
  <% @task.comments.each do |comment| %>
    <div class="comment_container">
      <p><%= comment.description %></p>
      <span> Commented by: comment.user_id.email </span>
    </div>
  <% end %>
  </div>

  <div class="bottom_left">
    asdasdasdasdasd
  </div>

  <div class="right_block2">
    <div class="description">
      <span>Task Description</span>
      <p><%= @task.description%></p>
    </div>  
    <div class="description">
      <span>Date due</span>
      <p><%=@task.due_date%></p>
    </div>
    <div class="description">
      <span>Time due</span>
      <p><%=@task.time%></p>
    </div>
    <div class="description">
      <span>Task Owner</span>
      <p><%=@task.owner%></p>
    </div>
    <div class="description">
      <span>Expected Hours</span>
      <p><%=@task.expected_hrs%></p>
    </div>
    <div class="description">
      <span>Task Status</span>
      <p><%= @task.status%></p>
    </div>
    <div class="description">
      <span>Requested by</span>
      <p><%= @task.requested_by%></p>
    </div>
    <div class="description">
      <span>Report Tag</span>
      <p><%= @task.report_tag%></p>
    </div>
  </div>

</div>
</div>

app/views/welcome/_slide1.html.erb
<div class="background">

  

</div>